### ISSUE TITLE
Modify number of PCs

### ISSUE THREAD

**Issue by FranjoIM** [zhangdaiwei/research#3]
Is there a way to calculate more than 4 PCs?

**Comment by daviddaiweizhang** [comment]
Yes, this can be done by setting `--dim_ref`.

For example, to get the top 10 PCs, you can use
`./fraposa_runner.py --dim_ref 10 --stu_filepref my_study_prefix my_reference_prefix`.

A complete list of options for FRAPOSA can be found by running `./fraposa_runner.py --help`.

**Comment by FranjoIM** [comment]
Thanks, I actually saw that an hour after asking the question, but forgot to remove the question.
