### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nebfield** [zhangdaiwei/research#6]
Thanks for making this great package! 

The repository has no LICENSE file, so I'm not sure if I'm allowed to modify or redistribute your code. By default publicly available but [unlicensed work is all rights reserved](https://opensource.stackexchange.com/a/1721).

Could you [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to the repository please? (hopefully something permissive like MIT 😅)

**Comment by daviddaiweizhang** [comment]
Thank you for your interest in FRAPOSA. The MIT license was just added.

**Comment by smlmbrt** [comment]
Thanks!
